---
- name: Install dummy Xserver for the webdriver (Debian-like)
  apt:
    name: "{{ item }}"
  with_items:
    - xvfb
    - x11vnc
  when: ansible_pkg_mgr == "apt"

- name: Install dummy Xserver for the webdriver (RedHat-like)
  yum:
    name: "{{ item }}"
  with_items:
    - xorg-x11-server-Xvfb
    - tigervnc-server-minimal
  when: ansible_pkg_mgr == "yum"

- name: Firefox installation
  unarchive:
    src: https://ftp.mozilla.org/pub/firefox/releases/44.0/linux-x86_64/en-GB/firefox-44.0.tar.bz2
    dest: /opt/
    remote_src: yes
    creates: /opt/firefox/firefox
  when: inventory_hostname in groups['load-driver']

- name: Add Firefox binary in PATH
  file: state=link dest=/usr/bin/firefox src=/opt/firefox/firefox
  when: inventory_hostname in groups['load-driver']

