---
- name: Software used with Selenium
  apt:
    name: "{{ item }}"
  with_items:
    - xvfb
  when: ansible_pkg_mgr == "apt"

- name: Firefox installation
  unarchive:
    src: https://ftp.mozilla.org/pub/firefox/releases/44.0/linux-x86_64/en-GB/firefox-44.0.tar.bz2
    dest: /opt/
    remote_src: yes
    creates: /opt/firefox/firefox

- name: Add Firefox binary in PATH
  file: state=link dest=/usr/bin/firefox src=/opt/firefox/firefox

