---
- name: Install dummy Xserver for the webdriver (Debian-like)
  apt:
    name: "{{ item }}"
  with_items:
    - xvfb
    - x11vnc
    - libgtk2.0-0
  when: ansible_pkg_mgr == "apt"

- name: Install dummy Xserver for the webdriver (RedHat-like)
  yum:
    name: "{{ item }}"
  with_items:
    - epel-release
    - xorg-x11-server-Xvfb
    - gtk2
  when: ansible_pkg_mgr == "yum" and inventory_hostname in groups['load-driver']

- name: Install extra convenient packages
  yum:
    name: x11vnc
    disable_gpg_check: yes
  when: ansible_pkg_mgr == "yum" and inventory_hostname in groups['load-driver']

- name: Firefox installation
  unarchive:
    src: https://ftp.mozilla.org/pub/firefox/releases/44.0/linux-x86_64/en-GB/firefox-44.0.tar.bz2
    dest: /opt/
    remote_src: yes
    creates: "{{ ff_install_path }}/firefox"
  when: inventory_hostname in groups['load-driver']

