---
- name: Create selenium user
  user:
    name: selenium
    system: yes
    shell: /bin/false
    home: /usr/local/share/selenium
    comment: "Selenium Browser autamation user"

- name: Get Selenium server
  get_url:
    url: "{{ selenium_url }}"
    dest: "/usr/local/share/selenium/selenium-server-standalone-{{ selenium_version }}.jar"
    mode: 0644

- name: Add Selenium Hub init script
  template:
    src: sysvinit-hub
    dest: /etc/init.d/selenium-hub
    mode: 0755
  when: inventory_hostname in groups['selenium-hub'] and ( ansible_service_mgr == 'upstart' or ansible_service_mgr == 'init' )
  notify: Restart Selenium hub

- name: Add Selenium Node init script
  template:
    src: sysvinit-node
    dest: /etc/init.d/selenium-node
    mode: 0755
  when: inventory_hostname in groups['load-driver'] and ( ansible_service_mgr == 'upstart' or ansible_service_mgr == 'init' )
  notify: Restart Selenium node

- name: Add Selenium Hub unit file
  template:
    src: unit-file_hub
    dest: "{{ systemd_unit_prefix }}/systemd/system/selenium-hub.service"
    mode: 0644
  when: inventory_hostname in groups['selenium-hub'] and ansible_service_mgr == 'systemd'
  notify:
    - Reload Systemd
    - Restart Selenium hub

- name: Add Selenium Node unit file
  template:
    src: unit-file_node
    dest: "{{ systemd_unit_prefix }}/systemd/system/selenium-node.service"
    mode: 0644
  when: inventory_hostname in groups['load-driver'] and ansible_service_mgr == 'systemd'
  notify:
    - Reload Systemd
    - Restart Selenium node

