---
- name: Restart Selenium hub
  service:
    name: selenium-hub
    state: restarted
    enabled: yes

- name: Restart Selenium node
  service:
    name: selenium-node
    state: restarted
    enabled: yes

