---
- name: Reset Tomcat connectors
  xml:
    file: "{{ tomcat_cfg_server }}"
    xpath: /Server/Service/Connector
    ensure: absent

- name: add HTTP Connector
  xml:
    file: "{{ tomcat_cfg_server }}"
    xpath: "{{ item }}"
  with_items:
    - /Server/Service/Connector/@port
    - /Server/Service/Connector/@protocol
    - /Server/Service/Connector/@maxPostSize
    - /Server/Service/Connector/@scheme

- name: Set Tomcat port (ansible-xml cannot handle this at the moment)
  replace:
    dest: "{{ tomcat_cfg_server }}"
    regexp: ' {{ item.attribute }}=""'
    replace: ' {{ item.attribute }}="{{ item.value }}" '
  with_items:
    - { attribute: port, value: "{{ tomcat_port }}" }
    - { attribute: protocol, value: "HTTP/1.1" }
    - { attribute: scheme, value: "http" }
    - { attribute: maxPostSize, value: "52428800" }
  notify: Restart Tomcat

- name: Set JAVA_HOME
  lineinfile:
    dest: "{{ tomcat_cfg_daemon }}"
    line: JAVA_HOME="{{ java_home }}"
    regexp: '^\s*JAVA_HOME\s*=.*$'
    create: yes
  notify: Restart Tomcat

- name: Set JAVA_OPTS
  lineinfile:
    dest: "{{ tomcat_cfg_daemon }}"
    line: JAVA_OPTS="$JAVA_OPTS -server -XX:MaxPermSize=512 -Xmx3G -Dmongo.config.host={{ groups['mongodb'][0] }}"
    create: yes
  notify: Restart Tomcat

- name: Remove all Tomcat webapps
  file: name="{{ catalina_home }}/webapps/{{ item }}" state=absent
  with_items:
    - alfresco-benchmark-server
    - alfresco-benchmark-server.war
  when: tomcat_clean == True

