---
- name: Remove all Tomcat webapps
  file: name="{{ catalina_home }}/webapps/{{ item }}" state=absent
  with_items:
    - alfresco-benchmark-server
    - alfresco-benchmark-server.war
  when: tomcat_clean == True

- name: Get Alfresco benchmark server artifact
  get_url:
    url: "{{ artifact_repo }}/{{ bm_server_path }}"
    dest: "{{ catalina_home }}/webapps/alfresco-benchmark-server.war"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    mode: 0644

